# Basis-Image
FROM python:3.9-slim

# Arbeitsverzeichnis
WORKDIR /app

# Anforderungen installieren
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Code kopieren
COPY . .

# Flask-App starten
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
