version: "3.8"

services:
  backend:
    build:
      context: ../backend
    ports:
      - "5000:5000"
    volumes:
      - ../db:/app/db
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
